<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \BlueFinch\Checkout\ViewModel\Assets $assetViewModel
 */
 $assetViewModel = $block->getAssetViewModel();
 $watermarkComponent = $assetViewModel->getDistViewFileUrl('BlueFinch_CheckoutFastlane::js/checkout/dist/components/Watermark.min.js');
 $paymentMethodComponent = $assetViewModel->getDistViewFileUrl('BlueFinch_CheckoutFastlane::js/checkout/dist/components/PaymentMethod.min.js');
?>

<script>
    window.bluefinchCheckout = window.bluefinchCheckout || {};

    window.bluefinchCheckout.belowEmailFields = window.bluefinchCheckout.belowEmailFields || {};
    window.bluefinchCheckout.overrides = window.bluefinchCheckout.overrides || {};
    window.bluefinchCheckout.paymentMethodsPrimary = window.bluefinchCheckout.paymentMethodsPrimary || {};

    window.bluefinchCheckout.belowEmailFields.FastlaneEmail = "<?= $escaper->escapeJs($watermarkComponent) ?>";
    window.bluefinchCheckout.paymentMethodsPrimary.FastlanePaymentMethod = "<?= $escaper->escapeJs($paymentMethodComponent) ?>";
</script>

<link rel="stylesheet" href="<?= $escaper->escapeHtmlAttr($assetViewModel->getDistViewFileUrl('BlueFinch_CheckoutFastlane::js/checkout/dist/styles.css')) ?>" />
