<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Gene\BetterCheckout\ViewModel\Assets $assetViewModel
 */
 $assetViewModel = $block->getAssetViewModel();
 $watermarkComponent = $assetViewModel->getDistViewFileUrl('Gene_BetterCheckoutFastlane::js/checkout/dist/components/Watermark.min.js');
 $paymentMethodComponent = $assetViewModel->getDistViewFileUrl('Gene_BetterCheckoutFastlane::js/checkout/dist/components/PaymentMethod.min.js');
?>

<script>
    window.geneCheckout = window.geneCheckout || {};

    window.geneCheckout.belowEmailFields = window.geneCheckout.belowEmailFields || {};
    window.geneCheckout.overrides = window.geneCheckout.overrides || {};
    window.geneCheckout.paymentMethodsPrimary = window.geneCheckout.paymentMethodsPrimary || {};

    window.geneCheckout.belowEmailFields.FastlaneEmail = "<?= $escaper->escapeJs($watermarkComponent) ?>";
    window.geneCheckout.paymentMethodsPrimary.FastlanePaymentMethod = "<?= $escaper->escapeJs($paymentMethodComponent) ?>";
</script>

<link rel="stylesheet" href="<?= $escaper->escapeHtmlAttr($assetViewModel->getDistViewFileUrl('Gene_BetterCheckoutFastlane::js/checkout/dist/styles.css')) ?>" />
